package br.com.pi_2026_1_etec.view.telas;


public class TelaMenuAlunos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuAlunos.class.getName());

    
    public TelaMenuAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnacess = new javax.swing.JButton();
        btnconfig = new javax.swing.JButton();
        btnnoturno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(775, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(7, 92, 110));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensEtec/Group 16 (1).png"))); // NOI18N
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 116, 180));

        jButton3.setBackground(new java.awt.Color(56, 69, 79));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensEtec/nivelMedio.png"))); // NOI18N
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 116, 180));

        jButton2.setBackground(new java.awt.Color(107, 44, 45));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensEtec/nivelDificil.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 116, 180));

        jButton1.setBackground(new java.awt.Color(146, 25, 19));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensEtec/nivelRandom.png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 116, 180));

        btnacess.setBackground(new java.awt.Color(3, 83, 103));
        btnacess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensEtec/Acess (1).png"))); // NOI18N
        jPanel1.add(btnacess, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 41, 42));

        btnconfig.setBackground(new java.awt.Color(195, 16, 12));
        btnconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensEtec/Config.png"))); // NOI18N
        btnconfig.addActionListener(this::btnconfigActionPerformed);
        jPanel1.add(btnconfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 41, 42));

        btnnoturno.setBackground(new java.awt.Color(0, 0, 0));
        btnnoturno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensEtec/noturno.png"))); // NOI18N
        btnnoturno.addActionListener(this::btnnoturnoActionPerformed);
        jPanel1.add(btnnoturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 41, 42));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensEtec/menu.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel2.setBackground(new java.awt.Color(10, 141, 168));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 80, 101));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Como funciona o jogo?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("possui mais dificuldade!");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 394, 280, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Selecione uma das dificuldades acima e pratique");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 356, 270, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("o quanto quiser! Seu resultado será guardado");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 280, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("para que você possa analisar questões que você");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 280, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfigActionPerformed

    private void btnnoturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnoturnoActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuAlunos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacess;
    private javax.swing.JButton btnconfig;
    private javax.swing.JButton btnnoturno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
